title: Tony Arthur
description: "Notes on security engineering, AI, and life outside it."
url: "https://www.iamtonyarthur.com"
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
permalink: /blog/:title/
plugins:
  - jekyll-feed
